<a href="https://colab.research.google.com/github/AurelNeff/Software/blob/master/Applied_ML_Summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 1 - Introduction
Introduction to Numpy, Recap of Python

In [2]:
#Imports
import numpy as np


In [ ]:
# 1.1 Python commands
myLst =[1,2,3, 'a', 'b', 'v']
myLst.append('newentry')
myLst.extend(['d','e','f'])
myLst.pop()
myLst.remove('a')
#Set can only have every value once!
#Which means, that setA & setB --> only the shared value is printed.
#If we substract one from each other, all values from set 1 are shown and if some of them are in set 2 they get skipped.
#Dictionary is nice, class style.

#Class handling
class Dogo:
  def __init__ (self, name):
    self.name = name
  
  def make_sound(self):
    print("Ruff")

class Catty:
  def __init__ (self, name):
    self.name = name
  
  def make_sound(self):
    print("Meow")


animal1 = Dogo(name='Pluto')
animal1.make_sound()
animal2 = Catty(name = 'Mika')
animal2.make_sound()

# 1.2 Introduction to Numpy
a = np.array([1,2,3])
a.dtype
a.shape
a.ndim
a.size
# type (A) = numpy array : a.type = integer
#filling an array with a certain value:
threes = np.full((4, 2), fill_value=3)
#Fill an array with a step size
r1 = np.arange(10,30,5)
#If fixed numper of elements is required, we prefer linspace
r2 = np.linspace(10,30,8)
#Basic operations are performed element wise, also between multiple arrays
a.min() #axis = 0 = row | axis = 1 = columns
a.max()
a.mean()
a.std()
A = np.array([1,2,3,4,5,6,7,8])
print(np.reshape(A, (2,4)))
#More stuff about sticking arrays with:
A = np.random.uniform(low=0, high=10, size=(2, 2))
B = np.random.uniform(low=0, high=1., size=(2, 2))
print(np.vstack((A,B)))
print(np.hstack((A,B))) #Stacking along second axis
#np.concatenate allows to specify the axis explicitly
#Splitting can be done by hsplit
#Be careful! Numpy differentiates between copy and view! b=a is a shallow copy

[[1 2 3 4]
 [5 6 7 8]]
[[2.60072299 5.92168921]
 [8.32158471 2.92797708]
 [0.43497899 0.54567555]
 [0.79736775 0.91202932]]
[[2.60072299 5.92168921 0.43497899 0.54567555]
 [8.32158471 2.92797708 0.79736775 0.91202932]]
